# Generated by Django 2.2.7 on 2019-11-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotesApp', '0003_quote_favoriters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favoriters',
            field=models.ManyToManyField(related_name='favorites', to='quotesApp.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_created', to='quotesApp.User'),
        ),
    ]
