# Generated by Django 2.2.7 on 2019-11-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ninja',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=45),
        ),
    ]
